#!/bin/bash

# umistit do /etc/init.d/rosstart a naimportovat do systemu
. /etc/init.d/functions

start () {
 . /home/odroid/robozor/devel/setup.bash
  export ROS_PACKAGE_PATH=/opt/ros/jade/share:/opt/ros/jade/stacks:/home/odroid/robozor/src:$ROS_PACKAGE_PATH
  export HOME="/home/odroid"
  export ROS_HOME="/home/odroid/.ros"

  export ROS_IP="0.0.0.0"
  LOG="/home/odroid/wb.log"

  echo -e "\n$(date +%Y:%m:%d-%T) - Starting daemon at system startup" >> $LOG

  echo "spousteni rosu ve screenu jako root..." >> $LOG
  screen -dmS ros roslaunch windowblind run.launch
}

case "$1" in
  start)
        start
	;;
esac
exit 0
